version: "3.3"
services:
  web:
    build: .
    container_name: knowledge_base
    working_dir: /project
    command: python manage.py runserver 0.0.0.0:3000
    ports:
      - "3000:3000"
    volumes:
      - .:/project